### ISSUE TITLE
И еще одно :)

### ISSUE THREAD

**Issue by KoIIIeY** [dosarkz/laravel-paybox#2]
Минимальная версия пыхи что это все работало - 7.4. 
На 7.1 - 7.3 - не заведется, потому что в них ошибки с типизацией. Извините что сразу не сказал, заметил только что на проде :(

**Comment by KoIIIeY** [comment]
И composer require guzzlehttp/guzzle обязателен

**Comment by KoIIIeY** [comment]
И ларавель только от 7, потому что в ларавелях ниже нет Http

**Comment by dosarkz** [comment]
thanks for it
